templateDir: ../templates
additionalProperties:
  supportsAsync: false
  additionalUsing: 
  - using Org.Eclipse.Digitaltwin.Basyx.V3.Clients.Model.Part1;
  - using Org.Eclipse.Digitaltwin.Basyx.V3.Clients.Model.Part2;
  netCoreProjectFile: true
  targetFramework: net8.0