templateDir: ../templates
additionalProperties:
  packageAuthors: Gerhard Sonnenberg
  packageCompany: DFKI GmbH
  packageTitle: Basys-Clients-V3.0.1
  packageCopyright: DFKI GmbH
  licenseId: MIT
  packageVersion: 1.0.0
  supportsAsync: false
  netCoreProjectFile: true
  targetFramework: net8.0