additionalProperties:
  java8: true
  useRuntimeException: true
  dateLibrary: java8
  sourceFolder: src/main/java
  useJarkartaEe: true
  legacyDiscriminatorBehavior: false
  disallowAdditionalPropertiesIfNotPresent: false
  supportUrlQuery: false
  artifactVersion: 0.0.1-SNAPSHOT
  testIdentifier: submodel-registry