---
openapi: "3.0.3"
info:
  title: "DotAAS Part 2 | HTTP/REST | Asset Administration Shell Registry Service\
    \ Specification"
  description: "The Full Profile of the Asset Administration Shell Registry Service\
    \ Specification as part of the Specification of the Asset Administration Shell:\
    \ Part 2. Publisher: Industrial Digital Twin Association (IDTA) April 2023"
  contact:
    name: "Industrial Digital Twin Association (IDTA)"
    email: "info@idtwin.org"
  license:
    name: "CC BY 4.0"
    url: "https://creativecommons.org/licenses/by/4.0/"
  version: "V3.0_SSP-001"
servers: []
paths:
  /shell-descriptors:
    get:
      tags:
      - "Asset Administration Shell Registry API"
      summary: "Returns all Asset Administration Shell Descriptors"
      operationId: "GetAllAssetAdministrationShellDescriptors"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/GetAllAssetAdministrationShellDescriptors/3/0"
      - "https://admin-shell.io/aas/API/GetAllAssetAdministrationShellDescriptorsByAssetKind/3/0"
      - "https://admin-shell.io/aas/API/GetAllAssetAdministrationShellDescriptorsByAssetType/3/0"
      parameters:
      - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/Limit"
      - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/Cursor"
      - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/AssetKind"
      - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/AssetType"
      responses:
        "200":
          description: "Requested Asset Administration Shell Descriptors"
          content:
            application/json:
              schema:
                $ref: "../../model-part2/openapi/api.yaml#/components/schemas/GetAssetAdministrationShellDescriptorsResult"
        "400":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/bad-request"
        "403":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/forbidden"
        "500":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/internal-server-error"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
    post:
      tags:
      - "Asset Administration Shell Registry API"
      summary: "Creates a new Asset Administration Shell Descriptor, i.e. registers\
        \ an AAS"
      operationId: "PostAssetAdministrationShellDescriptor"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/PostAssetAdministrationShellDescriptor/3/0"
      requestBody:
        description: "Asset Administration Shell Descriptor object"
        content:
          application/json:
            schema:
              $ref: "../../model-part2/openapi/api.yaml#/components/schemas/AssetAdministrationShellDescriptor"
        required: true
      responses:
        "201":
          description: "Asset Administration Shell Descriptor created successfully"
          content:
            application/json:
              schema:
                $ref: "../../model-part2/openapi/api.yaml#/components/schemas/AssetAdministrationShellDescriptor"
        "400":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/bad-request"
        "403":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/forbidden"
        "409":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/conflict"
        "500":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/internal-server-error"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
  /shell-descriptors/{aasIdentifier}:
    get:
      tags:
      - "Asset Administration Shell Registry API"
      summary: "Returns a specific Asset Administration Shell Descriptor"
      operationId: "GetAssetAdministrationShellDescriptorById"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/GetAssetAdministrationShellDescriptorById/3/0"
      parameters:
      - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/AssetAdministrationShellIdentifier"
      responses:
        "200":
          description: "Requested Asset Administration Shell Descriptor"
          content:
            application/json:
              schema:
                $ref: "../../model-part2/openapi/api.yaml#/components/schemas/AssetAdministrationShellDescriptor"
        "400":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/bad-request"
        "403":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/forbidden"
        "404":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/not-found"
        "500":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/internal-server-error"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
    put:
      tags:
      - "Asset Administration Shell Registry API"
      summary: "Updates an existing Asset Administration Shell Descriptor"
      operationId: "PutAssetAdministrationShellDescriptorById"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/PutAssetAdministrationShellDescriptorById/3/0"
      parameters:
      - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/AssetAdministrationShellIdentifier"
      requestBody:
        description: "Asset Administration Shell Descriptor object"
        content:
          application/json:
            schema:
              $ref: "../../model-part2/openapi/api.yaml#/components/schemas/AssetAdministrationShellDescriptor"
        required: true
      responses:
        "204":
          description: "Asset Administration Shell Descriptor updated successfully"
        "400":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/bad-request"
        "403":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/forbidden"
        "404":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/not-found"
        "500":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/internal-server-error"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
    delete:
      tags:
      - "Asset Administration Shell Registry API"
      summary: "Deletes an Asset Administration Shell Descriptor, i.e. de-registers\
        \ an AAS"
      operationId: "DeleteAssetAdministrationShellDescriptorById"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/DeleteAssetAdministrationShellDescriptorById/3/0"
      parameters:
      - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/AssetAdministrationShellIdentifier"
      responses:
        "204":
          description: "Asset Administration Shell Descriptor deleted successfully"
        "400":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/bad-request"
        "404":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/not-found"
        "500":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/internal-server-error"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
  /shell-descriptors/{aasIdentifier}/submodel-descriptors:
    parameters:
    - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/AssetAdministrationShellIdentifier"
    get:
      tags:
      - "Asset Administration Shell Registry API"
      summary: "Returns all Submodel Descriptors"
      operationId: "GetAllSubmodelDescriptorsThroughSuperpath"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/GetAllSubmodelDescriptors/3/0"
      parameters:
      - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/Limit"
      - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/Cursor"
      responses:
        "200":
          description: "Requested Submodel Descriptors"
          content:
            application/json:
              schema:
                $ref: "../../model-part2/openapi/api.yaml#/components/schemas/GetSubmodelDescriptorsResult"
        "400":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/bad-request"
        "403":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/forbidden"
        "404":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/not-found"
        "500":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/internal-server-error"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
    post:
      tags:
      - "Asset Administration Shell Registry API"
      summary: "Creates a new Submodel Descriptor, i.e. registers a submodel"
      operationId: "PostSubmodelDescriptor-ThroughSuperpath"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/PostSubmodelDescriptor/3/0"
      requestBody:
        description: "Submodel Descriptor object"
        content:
          application/json:
            schema:
              $ref: "../../model-part2/openapi/api.yaml#/components/schemas/SubmodelDescriptor"
        required: true
      responses:
        "201":
          description: "Submodel Descriptor created successfully"
          content:
            application/json:
              schema:
                $ref: "../../model-part2/openapi/api.yaml#/components/schemas/SubmodelDescriptor"
        "400":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/bad-request"
        "403":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/forbidden"
        "404":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/not-found"
        "409":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/conflict"
        "500":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/internal-server-error"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
  /shell-descriptors/{aasIdentifier}/submodel-descriptors/{submodelIdentifier}:
    parameters:
    - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/AssetAdministrationShellIdentifier"
    - $ref: "../../model-part2/openapi/api.yaml#/components/parameters/SubmodelIdentifier"
    get:
      tags:
      - "Asset Administration Shell Registry API"
      summary: "Returns a specific Submodel Descriptor"
      operationId: "GetSubmodelDescriptorByIdThroughSuperpath"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/GetSubmodelDescriptorById/3/0"
      responses:
        "200":
          description: "Requested Submodel Descriptor"
          content:
            application/json:
              schema:
                $ref: "../../model-part2/openapi/api.yaml#/components/schemas/SubmodelDescriptor"
        "400":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/bad-request"
        "403":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/forbidden"
        "404":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/not-found"
        "500":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/internal-server-error"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
    put:
      tags:
      - "Asset Administration Shell Registry API"
      summary: "Updates an existing Submodel Descriptor"
      operationId: "PutSubmodelDescriptorByIdThroughSuperpath"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/PutSubmodelDescriptorById/3/0"
      requestBody:
        description: "Submodel Descriptor object"
        content:
          application/json:
            schema:
              $ref: "../../model-part2/openapi/api.yaml#/components/schemas/SubmodelDescriptor"
        required: true
      responses:
        "204":
          description: "Submodel Descriptor updated successfully"
        "400":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/bad-request"
        "403":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/forbidden"
        "404":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/not-found"
        "500":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/internal-server-error"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
    delete:
      tags:
      - "Asset Administration Shell Registry API"
      summary: "Deletes a Submodel Descriptor, i.e. de-registers a submodel"
      operationId: "DeleteSubmodelDescriptorByIdThroughSuperpath"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/DeleteSubmodelDescriptorById/3/0"
      responses:
        "204":
          description: "Submodel Descriptor deleted successfully"
        "400":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/bad-request"
        "404":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/not-found"
        "500":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/internal-server-error"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
  /description:
    get:
      tags:
      - "Description API"
      summary: "Returns the self-describing information of a network resource (ServiceDescription)"
      operationId: "GetDescription"
      x-semanticIds:
      - "https://admin-shell.io/aas/API/Descriptor/GetDescription/3/0"
      responses:
        "200":
          description: "Requested Description"
          content:
            application/json:
              schema:
                $ref: "../../model-part2/openapi/api.yaml#/components/schemas/ServiceDescription"
        "403":
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/forbidden"
        default:
          $ref: "../../model-part2/openapi/api.yaml#/components/responses/default"
