version: '3.6'

services:

  portainer:
    image: portainer/portainer-ce:2.18.2
    container_name: portainer
    command: --admin-password-file=/secrets/admin-password
    ports: 
      - "8084:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./portainer/admin-password:/secrets/admin-password

  aas-registry:
    image:  eclipsebasyx/aas-registry-log-mem:${BASYX_VERSION}
    restart: always
    container_name: aas-registry
    ports:
    - "8083:8080"
    environment:
      BASYX_CORS_ALLOWED_ORIGINS: '*'
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

  submodel-registry:
    image:  eclipsebasyx/submodel-registry-log-mem:${BASYX_VERSION}
    restart: always
    container_name: submodel-registry
    ports:
    - 8082:8080
    environment:
      BASYX_CORS_ALLOWED_ORIGINS: '*'
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

  aas-environment:
    image: eclipsebasyx/aas-environment:${BASYX_VERSION}
    container_name: aas-environment
    restart: always
    ports:
    - 8081:8081
    environment:
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://aas-registry:8080
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://submodel-registry:8080
      BASYX_AASREPOSITORY_FEATURE_AASXUPLOAD_ENABLED: "true"   
      BASYX_CORS_ALLOWED_ORIGINS: '*'
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_EXTERNALURL: http://localhost:8081
    #  BASYX_ENVIRONMENT: file:/tmp/aasx/
      DEBUG: "true"
    #volumes:
    #- ./aasx/:/tmp/aasx/:ro
    depends_on:
      aas-registry:
        condition: service_healthy
      submodel-registry:
        condition: service_healthy

  aas-gui:
    image: eclipsebasyx/aas-gui:${AAS_WEBUI_VERSION}
    container_name: aas-gui
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_AAS_REGISTRY_PATH: http://localhost:8083
      VITE_SUBMODEL_REGISTRY_PATH: http://localhost:8082
      VITE_AAS_REPO_PATH: http://localhost:8081/shells
      VITE_SUBMODEL_REPO_PATH: http://localhost:8081/submodels
      VITE_CD_REPO_PATH: http://localhost:8081/concept-descriptions
    ports:
    - 3000:3000
    depends_on:
      aas-registry:
        condition: service_healthy
      submodel-registry:
        condition: service_healthy    
      aas-environment:
        condition: service_healthy



