additionalProperties:
  java8: true
  useRuntimeException: true
  dateLibrary: java8
  sourceFolder: src/main/java
  useJarkartaEe: true
  legacyDiscriminatorBehavior: false
  disallowAdditionalPropertiesIfNotPresent: false
  supportUrlQuery: false
  groupId: org.eclipse.digitaltwin.basyx.v3.clients
  artifactId: basyx-java-clients
  artifactVersion: 0.2.0-SNAPSHOT
  licenseName: MIT
  develperName: Gerhard Sonnenberg
  developerEmail: gerhard.sonnenberg@dfki.de
  developerOrganization: DFKI GmbH
  developerOrganizationUrl: https://www.dfki.de
