additionalProperties:
  npmName: "@basys/v3-client-ts"
  npmVersion: 0.2.0
  snapshot: true
  prefixParameterInterfaces: true
  modelPrefix: "part1"
files:
  model/index.mustache:
    templateType: SupportingFiles
    destinationFilename: models/part1/index.ts
  model/ObjectSerializerDefs.mustache:
    templateType: SupportingFiles
    destinationFilename: models/part1/ObjectSerializerDefs.ts