additionalProperties:
  npmName: "@basyx/v3-client-ts"
  npmVersion: 0.2.0
  snapshot: true
  prefixParameterInterfaces: true
  supportsES6: true
  stringEnums: true
  useSingleRequestParameter: false
  importMappings:
  - name: SubmodelElement
    prefix: part1  
  - name: SubmodelElementValue
    prefix: part2
  - name: Submodel
    prefix: part1
  - name: SubmodelElementMetadata
    prefix: part2
  - name: SubmodelValue
    prefix: part2
  - name: SubmodelMetadata
    prefix: part2
  - name: OperationResultValueOnly
    prefix: part2
  - name: OperationRequestValueOnly
    prefix: part2
  - name: OperationRequest
    prefix: part2
  - name: OperationResult
    prefix: part2
  - name: Reference
    prefix: part1
  - name: BaseOperationResult
    prefix: part2
  - name: ServiceDescription
    prefix: part2
  - name: GetSubmodelsValueResult
    prefix: part2
  - name: GetReferencesResult
    prefix: part2
  - name: GetPathItemsResult
    prefix: part2
  - name: GetSubmodelsMetadataResult
    prefix: part2
  - name: GetSubmodelsResult
    prefix: part2
  - name: GetSubmodelElementsResult
    prefix: part2
  - name: GetSubmodelElementsValueResult
    prefix: part2
  - name: GetSubmodelElementsMetadataResult
    prefix: part2
files:
  types/ObjectParamAPI.mustache:
    templateType: SupportingFiles
    destinationFilename: types/smrepo/ObjectParamAPI.ts
  types/ObservableAPI.mustache:
    templateType: SupportingFiles
    destinationFilename: types/smrepo/ObservableAPI.ts
  types/PromiseAPI.mustache:
    templateType: SupportingFiles
    destinationFilename: types/smrepo/PromiseAPI.ts