additionalProperties:
  java8: true
  dateLibrary: java8
  sourceFolder: src/main/java
  useJarkartaEe: true
  legacyDiscriminatorBehavior: false
  disallowAdditionalPropertiesIfNotPresent: false
  supportUrlQuery: false
  testIdentifier: submodel-repository